$ANSIBLE_VAULT;1.1;AES256
38623631633337653839393162306432373135333463326134643835313939353137303363613134
6466613262346439616162326433366431636133306537320a626331663066663963653533643363
38303731383735303162336632666432306632643336616666326266636163626634616162336531
3239363065613036300a313532623366383136343835323635396365623461356337653938313661
66336262626362353038636363393461306261373736323237356562306565633063313036336630
31393033303666373735336431313064316339353638616236616133663034356338383338346662
31613334393334383733626235323962326163393637656263653366636537356662346366636663
37643763353338396336
